server:
  port: 8762

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pvduc-dev/config-repo.git
          username: pvduc.dev@gmail.com
          password: quacol2019
    bus:
      enabled: true
  kafka:
    bootstrap-servers: 35.220.136.178:9092
